target_patient_ids:
  - "ballantyne-flavia-indira"
  - "ballantyne-kelvin-hans"
  - "ballantyne-terry-bob"
  - "banks-jeramy-ezra"
  - "banks-jonas-cary"
  - "belger-remedios"
  - "black-kerry-dougal"
  - "boulton-annika"
  - "britton-brian-edwin"
  - "callow-veronica-connie"
  - "cane-cheyenne-elaina"
  - "davis-juan"
  - "dietrich-blake-louis"
  - "dietrich-diedre-alicia"
  - "dietrich-kimbra-althea"
  - "dietrich-phillipa-grace"
  - "foreman-caterina"
  - "frost-rhett-kent"
  - "hampton-jenice"
  - "italia-sofia"
  - "johnson-joyce"
  - "little-rose-gretal"
  - "lynch-alyce-shauna"
  - "mackay-elliott"
  - "mackay-fritz"
  - "martin-shawn"
  - "moffitt-heath-igor"
  - "moylan-brock"
  - "odonnell-gillian"
  - "potts-felix-ernie"
  - "robson-adam"
  - "thomson-mika"
  - "veitch-beau-bradley"
  - "veitch-miles-dudley"
  - "veitch-savannah-sheena"
  - "irvine-ronny-lawrence"
  - "banks-mia-leanne"
  - "italia-sofia-suppressed-birthDate"
  - "italia-sofia-suppressed-gender"
  - "italia-sofia-missing-gender"
  - "italia-sofia-missing-name"
  - "italia-sofia-missing-birthDate"
  - "baby-banks-john"
  - "italia-sofia-missing-identifier"
  - "baratz-toni2"
  - "baratz-toni3"
  - "1078d551-7be2-49f7-a122-c230b8757f2f"
  - "archibald-dante"

mapping:
  allergies:
  - from: START
    to: recordedDate
  - from: STOP
    to: clinicalStatus_code
  - from: PATIENT
    to: patient_reference_id
  - from: ENCOUNTER
    to: encounter_display
  - from: CODE
    to: code_coding1_code
  - from: SYSTEM
    to: code_coding1_system
  - from: DESCRIPTION
    to: code_coding1_display
  - from: TYPE
    to: type
  - from: CATEGORY
    to: category
  - from: REACTION1
    to: reaction_manifestation1_display
  - from: DESCRIPTION1
    to: reaction_manifestation1_text
  - from: SEVERITY1
    to: reaction_severity
  - from: REACTION2
    to: reaction_manifestation2_display
  - from: DESCRIPTION2
    to: reaction_manifestation2_text
  - from: SEVERITY2
    to: reaction_severity
  encounters:
  - from: Id
    to: id
  - from: START
    to: period_start
  - from: STOP
    to: period_end
  - from: PATIENT
    to: subject_reference_id
  - from: ORGANIZATION
    to: serviceProvider_reference_id
  - from: PROVIDER
    to: participant1_individual_reference_id
  - from: PAYER
    to: serviceProvider_reference_id
  - from: ENCOUNTERCLASS
    to: class_code
  - from: CODE
    to: type_code
  - from: DESCRIPTION
    to: type_display
  - from: BASE_ENCOUNTER_COST
    to: total_claim_cost
  - from: TOTAL_CLAIM_COST
    to: total_claim_cost
  - from: PAYER_COVERAGE
    to: payer_coverage
  - from: REASONCODE
    to: reasonCode_code
  - from: REASONDESCRIPTION
    to: reasonCode_display
  organizations:
  - from: Id
    to: id
  - from: NAME
    to: name
  - from: ADDRESS
    to: address1_line1
  - from: CITY
    to: address1_city
  - from: STATE
    to: address1_state
  - from: ZIP
    to: address1_postalCode
  - from: LAT
    to: TODO
  - from: LON
    to: TODO
  - from: PHONE
    to: telecom1_value
  - from: REVENUE
    to: TODO
  - from: UTILIZATION
    to: TODO
  medications:
  - from: START
    to: TODO
  - from: STOP
    to: TODO
  - from: PATIENT
    to: TODO
  - from: PAYER
    to: TODO
  - from: ENCOUNTER
    to: TODO
  - from: CODE
    to: code_coding1_code
  - from: DESCRIPTION
    to: code_coding1_display
  - from: BASE_COST
    to: TODO
  - from: PAYER_COVERAGE
    to: TODO
  - from: DISPENSES
    to: TODO
  - from: TOTALCOST
    to: TODO
  - from: REASONCODE
    to: TODO
  - from: REASONDESCRIPTION
    to: TODO
  immunizations:
  - from: DATE
    to: TODO
  - from: PATIENT
    to: TODO
  - from: ENCOUNTER
    to: TODO
  - from: CODE
    to: TODO
  - from: DESCRIPTION
    to: TODO
  - from: BASE_COST
    to: TODO
  observations:
  - from: DATE
    to: TODO
  - from: PATIENT
    to: TODO
  - from: ENCOUNTER
    to: TODO
  - from: CATEGORY
    to: TODO
  - from: CODE
    to: TODO
  - from: DESCRIPTION
    to: TODO
  - from: VALUE
    to: TODO
  - from: UNITS
    to: TODO
  - from: TYPE
    to: TODO
  procedures:
  - from: START
    to: TODO
  - from: STOP
    to: TODO
  - from: PATIENT
    to: TODO
  - from: ENCOUNTER
    to: TODO
  - from: SYSTEM
    to: TODO
  - from: CODE
    to: TODO
  - from: DESCRIPTION
    to: TODO
  - from: BASE_COST
    to: TODO
  - from: REASONCODE
    to: TODO
  - from: REASONDESCRIPTION
    to: TODO
  conditions:
  - from: START
    to: TODO
  - from: STOP
    to: TODO
  - from: PATIENT
    to: TODO
  - from: ENCOUNTER
    to: TODO
  - from: SYSTEM
    to: TODO
  - from: CODE
    to: TODO
  - from: DESCRIPTION
    to: TODO

rename_files:
  allergies: AU Core Sample Data - AllergyIntolerance
  conditions: AU Core Sample Data - Condition
  encounters: AU Core Sample Data - Encounter
  immunizations: AU Core Sample Data - Immunization
  medications: AU Core Sample Data - Medication
  observations: AU Core Sample Data - Observation
  organizations: AU Core Sample Data - Organization
  procedures: AU Core Sample Data - Procedure

add_ids_column:

delete_files:
  - careplans
  - claims
  - claims_transactions
  - devices
  - imaging_studies
  - patients
  - payers
  - payer_transitions
  - providers
  - supplies

