services:
  synthea:
    build:
      context: .
    volumes:
      - ./output:/output
      - ./modules:/modules
    command: java -jar synthea-with-dependencies.jar --exporter.csv.export=true -p 1 -d modules/ 

