name: Build and save
on:
  workflow_dispatch:
jobs:
  BuildSteps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Initiate submodules
        run: git submodule update --init
      - name: Run Generate pipeline
        run: make pipeline-ci
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: result-artifact
          path: results/results.tar.gz
